/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package week04;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.nio.file.Paths;
import java.security. AlgorithmParameterGenerator;
import java.security.AlgorithmParameters;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security. KeyPairGenerator;
import java.security.MessageDigest;
import java.security. PublicKey;
import java.security.spec.X509EncodedKeySpec;
import java.util.Arrays;
import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.KeyAgreement;
import javax.crypto.SecretKey;
import javax.crypto.interfaces.DHPublicKey;
import javax.crypto.spec.DHParameterSpec;
import javax.crypto.spec.SecretKeySpec;

/**
 *
 * @author levan
 */
public class frm_Bob extends javax.swing.JFrame {

    /**
     * Creates new form frm_Bob
     */
    public frm_Bob() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_make_secret_key = new javax.swing.JButton();
        btn_encrypt_secret_key = new javax.swing.JButton();
        btn_encrypt_decrypt = new javax.swing.JButton();
        txt_encrypt_shared_secret = new javax.swing.JTextField();
        txt_shared_secret = new javax.swing.JTextField();
        txt_alice_key = new javax.swing.JTextField();
        txt_bob_key = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_bob_key_generate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_alice_key_display = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_make_secret_key.setText("make secret key");
        btn_make_secret_key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_make_secret_keyActionPerformed(evt);
            }
        });

        btn_encrypt_secret_key.setText("encrypt secret key");
        btn_encrypt_secret_key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encrypt_secret_keyActionPerformed(evt);
            }
        });

        btn_encrypt_decrypt.setText("Run encrypt/dencrypt form");
        btn_encrypt_decrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encrypt_decryptActionPerformed(evt);
            }
        });

        jLabel1.setText("Alice's key");

        jLabel2.setText("Bob's key");

        btn_bob_key_generate.setText("Bob's_key_generate");
        btn_bob_key_generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bob_key_generateActionPerformed(evt);
            }
        });

        jLabel3.setText("Shared Secret");

        btn_alice_key_display.setText("Alice's key display");
        btn_alice_key_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alice_key_displayActionPerformed(evt);
            }
        });

        jLabel4.setText("Encryot Shared Secret");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_encrypt_shared_secret)
                            .addComponent(txt_alice_key)
                            .addComponent(txt_bob_key)
                            .addComponent(txt_shared_secret, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_make_secret_key, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_encrypt_secret_key, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_alice_key_display, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_bob_key_generate, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_encrypt_decrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_bob_key_generate)
                    .addComponent(txt_bob_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_alice_key_display)
                    .addComponent(txt_alice_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_shared_secret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_make_secret_key)
                    .addComponent(jLabel3))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_encrypt_shared_secret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_encrypt_secret_key)
                    .addComponent(jLabel4))
                .addGap(61, 61, 61)
                .addComponent(btn_encrypt_decrypt)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

         KeyAgreement bobKeyAgree;
        PublicKey alicePubKey;
        SecretKey bobDesKey;
        Cipher bobCipher;
    private void btn_encrypt_decryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encrypt_decryptActionPerformed
        // TODO add your handling code here:
        frm_DESCS des = new frm_DESCS();
        des.setVisible(true);
    }//GEN-LAST:event_btn_encrypt_decryptActionPerformed

    private void btn_bob_key_generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bob_key_generateActionPerformed
        // TODO add your handling code here:
        
        try {
        boolean read = false;
        java.nio.file.Path dirPath = Paths.get("src/week_04");
        if (!java.nio.file.Files.exists(dirPath)) {
        java.nio.file.Files.createDirectories (dirPath);
        }
        while (!read) {
        try (FileInputStream fis =
        new FileInputStream (dirPath.resolve("A.pub").toFile())) {
        read = true;
        } catch (Exception ex) {
        ex.printStackTrace();
        }
        }
        byte[] alicePubKeyEnc;
        try (FileInputStream fis =
        new FileInputStream(dirPath.resolve("A.pub").toFile())) {
        alicePubKeyEnc = new byte[fis.available()];
        fis.read(alicePubKeyEnc);
        }
        KeyFactory bobKeyFac=  KeyFactory.getInstance("DH");
        X509EncodedKeySpec x509KeySpec =
        new X509EncodedKeySpec (alicePubKeyEnc);
        alicePubKey = bobKeyFac.generatePublic(x509KeySpec);
        DHParameterSpec dhParamSpec = ((DHPublicKey) alicePubKey).getParams();
        KeyPairGenerator bobKpairGen=  KeyPairGenerator.getInstance("DH");
        bobKpairGen.initialize (dhParamSpec);
        KeyPair bobKpair = bobKpairGen.generateKeyPair();
        bobKeyAgree= KeyAgreement.getInstance("DH");
        bobKeyAgree.init (bobKpair.getPrivate());
        byte[] bobPubKeyEnc=  bobKpair.getPublic().getEncoded();
        try (FileOutputStream fos =
        new FileOutputStream(dirPath.resolve("B.pub").toFile())) {
        fos.write(bobPubKeyEnc);
        }
        txt_bob_key.setText(java.util.Base64.getEncoder()
        .encodeToString (bobPubKeyEnc));
        } catch (Exception ex) {
        ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_bob_key_generateActionPerformed

    private void btn_make_secret_keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_make_secret_keyActionPerformed
        // TODO add your handling code here:
        try {
        bobKeyAgree.doPhase (alicePubKey, true);
        byte[] bobSharedSecret = bobKeyAgree.generateSecret();
        txt_shared_secret.setText (CryptoUtil.toHexString(bobSharedSecret));
        } catch (Exception ex) {
        ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_make_secret_keyActionPerformed

    private void btn_encrypt_secret_keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encrypt_secret_keyActionPerformed
        // TODO add your handling code here:
        try {
            bobKeyAgree.doPhase (alicePubKey, true);
            byte[] sharedSecret = bobKeyAgree.generateSecret();
            txt_encrypt_shared_secret.setText (CryptoUtil.toHexString(sharedSecret));
            MessageDigest sha256 = MessageDigest.getInstance("SHA-256");
            byte[] desKeyBytes = Arrays.copyOf(sha256.digest (sharedSecret), 8);
            SecretKeySpec desKeySpec = new SecretKeySpec (desKeyBytes, "DES");
            txt_encrypt_shared_secret.setText (Base64.getEncoder()
            .encodeToString (desKeySpec.getEncoded()));
            String fileName = "src/week_04/B.txt";
            try (BufferedWriter bw= new BufferedWriter(new FileWriter (fileName))) {
            bw.write(Base64.getEncoder().encodeToString(desKeySpec.getEncoded()));
            }
            } catch (Exception ex) {
            ex.printStackTrace();
            }
    }//GEN-LAST:event_btn_encrypt_secret_keyActionPerformed

    private void btn_alice_key_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alice_key_displayActionPerformed

            try {
            byte[] bkeyP;
            try (FileInputStream fis =
            new FileInputStream (Paths.get("src/week_04/A.pub").toFile())) {
            bkeyP=  new byte[fis.available()];
            fis.read(bkeyP);
            }
            txt_alice_key.setText (bkeyP.toString());
            } catch (Exception ex) {
            ex.printStackTrace();
            }
                  // TODO add your handling code here:
    }//GEN-LAST:event_btn_alice_key_displayActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Bob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alice_key_display;
    private javax.swing.JButton btn_bob_key_generate;
    private javax.swing.JButton btn_encrypt_decrypt;
    private javax.swing.JButton btn_encrypt_secret_key;
    private javax.swing.JButton btn_make_secret_key;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_alice_key;
    private javax.swing.JTextField txt_bob_key;
    private javax.swing.JTextField txt_encrypt_shared_secret;
    private javax.swing.JTextField txt_shared_secret;
    // End of variables declaration//GEN-END:variables
}
